### ISSUE TITLE
IRI to use in schemas referring to ontology terms

### ISSUE THREAD

**Issue by bartkl** [Netbeheer-Nederland/doc-uri-policy#21]
Suppose I have the following LinkML schema:

```yaml
id: https://data.nbnl.info/schema/data-product/netburen
version: 1.0.1
name: netburen
prefixes:
  nbnl: https://id.nbnl.info/taxonomy/energiesysteembeheer/
  cimnl: https://id.nbnl.info/ont/cim-nl/
classes:
  MarketEvaluationPoint:
    class_uri: cim:MarketEvaluationPoint
    description: The identification of an entity where energy products are measured
      or computed.
    from_schema: https://cim.ucaiug.io/ns#TC57CIM.IEC62325.MarketManagement
    exact_mappings:
    - nbnl:aansluiting
    is_a: UsagePoint
```

Let's focus on the ontology terms used from the ontologies listed in the `prefixes` block. I am using the version-less `id` IRIs to refer to the real-world entities the model elements in this schema correspond to semantically. However, this might be erroneous.

For example: should the `class_uri` point to the IRI of the real-world entity to tell you what it is? Or should it point to a (versioned) definition of that real-world entity? In the latter case a versioned `data` IRI must be used.

In fact, nowhere in my strategy have I dealt with the meaning of the `data` IRI of an ontology term. This corresponds to its formal definition (the ontology, really), but that is distinct from its mere identity, _and_ opposed to its identity it is versioned.

Finally, this seems to have to do with metaphysical presuppositions regarding universals (ontology terms represent universals). In the case of realism, universals are real and could therefore probably be assigned IRIs independent from any context/mind/conceptualization.

Conceptualism on the other hand denies the existence of universals in this "real" sense, and claims they are inherently conceptualizations, bound to some context or mind. In this case, the identity of ontology terms are inherently equivalent with their definition, i.e. they are information resources and must use `data` IRIs.

There is also nominalism, which states universals are completely unreal and are mere names. Within the scope of our purposes, I think nominalism and conceptualism are interchangeable.

**Think about this.**
